# -*- mode: ruby -*-
# vi: set ft=ruby :

VAGRANTFILE_API_VERSION = "2"

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|
  config.vm.box = "ubuntu/trusty64"

  config.vm.define :devel do |devel| 
      devel.vm.hostname = "devel"
      devel.vm.network :private_network, ip: "10.0.0.23"
      devel.vm.provider "virtualbox" do |vb|
          vb.customize ["modifyvm", :id, "--memory", 1024]
      end
  end

  config.vm.network :forwarded_port, guest: 3222, host: 3222
end
